### ISSUE TITLE
Requests Getting 500 In Unity

### ISSUE THREAD

**Issue by hekemp** [dgkanatsios/AzureFunctionsNodeLeaderboards-Cosmos#3]
Hello! I'm trying to create a project similar to this and I'm trying to use your project as a base reference. However, after deploying your server via the one click deployment and running your local project, I can't get any of the requests aside from listing the top 10 scores to work. The Post request is my current point of focus, and I've tried several different means of getting it to work, but to no avail.

My PostScoreInternal code is now (I know a lot of things are redundant/bad practice, like using x-mas-client-principal-id instead of the global var, but I wanted to try and isolate as many causes of errors as possible)
```
		string json = JsonUtility.ToJson(instance);
		Debug.Log (json);
		byte[] bytes = Encoding.UTF8.GetBytes(json);
		using (UnityWebRequest www = UnityWebRequest.Put(GetLeaderboardsAPIURL() + "scores", bytes))
		{
			www.uploadHandler.contentType = "application/json";
			www.SetRequestHeader("Content-Type", "application/json");
			www.SetRequestHeader ("Accept", "application/json");
			www.SetRequestHeader("x-ms-client-principal-id", userID);
			www.SetRequestHeader("x-ms-client-principal-name", username);
			www.SetRequestHeader("Postman-Token", "bc150ca4-43fe-4535-a620-1e84542eb138");
			www.SetRequestHeader("Cache-Control", "no-cache");

			Debug.Log (www.uploadHandler.data);
			Debug.Log (www.uploadHandler.contentType);
			Debug.Log(www.uploadHandler.ToString());

			www.method = UnityWebRequest.kHttpVerbPOST;
			www.chunkedTransfer = true;

			Debug.Log(www.GetRequestHeader ("Content-Type"));

			yield return www.SendWebRequest();

			if (www.isNetworkError || www.isHttpError) {
				Debug.LogError (www.isNetworkError ? "NETWORK ERROR" : "HTTP ERROR");
				Debug.LogError ("STATUS: " + www.responseCode);
				Debug.LogError (www.error);
				Debug.LogError (www.downloadHandler.text);
			}
		}
```

I've also tried
```
		string json = JsonUtility.ToJson(instance);
		Debug.Log (json);
		byte[] bytes = Encoding.UTF8.GetBytes(json);
		using (UnityWebRequest www = UnityWebRequest.Post(GetLeaderboardsAPIURL() + "scores", json))
		{
			www.uploadHandler.contentType = "application/json";
			www.SetRequestHeader("Content-Type", "application/json");
			www.SetRequestHeader ("Accept", "application/json");
			www.SetRequestHeader("x-ms-client-principal-id", userID);
			www.SetRequestHeader("x-ms-client-principal-name", username);
			www.SetRequestHeader("Postman-Token", "bc150ca4-43fe-4535-a620-1e84542eb138");
			www.SetRequestHeader("Cache-Control", "no-cache");

			Debug.Log (www.uploadHandler.data);
			Debug.Log (www.uploadHandler.contentType);
			Debug.Log(www.uploadHandler.ToString());
			Debug.Log(www.GetRequestHeader ("Content-Type"));

			yield return www.SendWebRequest();

			if (www.isNetworkError || www.isHttpError) {
				Debug.LogError (www.isNetworkError ? "NETWORK ERROR" : "HTTP ERROR");
				Debug.LogError ("STATUS: " + www.responseCode);
				Debug.LogError (www.error);
				Debug.LogError (www.downloadHandler.text);
			}
		}
```

Neither of which have yielded success. Any insight on to why this would occur would be greatly appreciated.

**Comment by dgkanatsios** [comment]
Hi there! Are there any logs on the Azure Functions themselves to indicate more about the error?

**Comment by hekemp** [comment]
From monitoring the app, I can see that success is true while it returns 500. I can't find any other logs about the Azure Functions in terms of what the exact request it received was.

**Comment by dgkanatsios** [comment]
Are you also using Application Insights (it’s activated with the ARM template). They should give you more details regarding the error

**Comment by hekemp** [comment]
I've looked inside Application Insights, but since the app technically doesn't "fail" I don't get any errors
<img width="953" alt="Screen Shot 2019-03-27 at 9 34 05 AM" src="https://user-images.githubusercontent.com/14400687/55084801-8d15fb80-5073-11e9-85ac-a820b17489e8.png">

**Comment by dgkanatsios** [comment]
I’ll try a redeployment and have a look myself. Thanks!

**Comment by dgkanatsios** [comment]
<img width="720" alt="Capture" src="https://user-images.githubusercontent.com/8256138/55092194-caea4280-50ba-11e9-997c-a6dd13eee307.PNG">
Just deployed it and seems to be working fine from the provided Unity project. Url is https://gkanatsiosunity.azurewebsites.net/ in case you want to try. I'll take a look at your code.

**Comment by hekemp** [comment]
Strange, it's still not working on my machine. Do you mind if I ask what version of Unity you're using? I've a sneaking suspicion that it's either a Unity version issue or an OS issue (I'm going to go try it on a Windows computer now to check that one out)

**Comment by dgkanatsios** [comment]
Tried that on Unity 5.6 (an old one, I had set it up for backwards compatibility). Can you try to remove some headers? For instance, I think that these two

```csharp
www.SetRequestHeader("Postman-Token", "bc150ca4-43fe-4535-a620-1e84542eb138");
www.SetRequestHeader("Cache-Control", "no-cache");
```

are unnecessary.

**Comment by hekemp** [comment]
The sample project worked on a Windows machine with 2017.4.24f1 LTS. I'm going to try and install that version on my Mac, and if that doesn't work for the sample project, I think it might be actually a Mac issue. I'll let you know if this is the case once that finishes installing.

**Comment by hekemp** [comment]
I just tested this on my Mac with 2017.4.24f1 LTS (instead of Unity 2017.3.1f1) and it works perfectly now. Sorry for the confusion -- looks like UnityWebRequest has a few errors in that version of Unity (and a few others, I assume)

**Comment by dgkanatsios** [comment]
Awesome - are you ok to close this issue? Feel free to open another one if there’s a need. Thanks for trying out the library!

**Comment by hekemp** [comment]
Yep, it's all working well now! Thanks again for making such a nice library :)
